# Generated by Django 3.2.7 on 2021-10-04 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default='1')),
                ('priority', models.IntegerField(default='1')),
                ('created_by', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
