# Generated by Django 3.2.7 on 2021-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.IntegerField(blank=True),
        ),
    ]
