# Generated by Django 3.2.7 on 2021-09-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'TODO'), (2, 'READY'), (3, 'IN PROGRESS'), (4, 'COMPLETED')], default='1'),
        ),
    ]
