# Generated by Django 3.2.7 on 2021-09-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
