# Generated by Django 3.2.7 on 2021-10-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0002_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'TO_DO'), (2, 'READY'), (3, 'IN_PROGRESS'), (4, 'COMPLETED')], default=1),
        ),
    ]
