# Generated by Django 3.2.7 on 2021-10-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0002_rename_created_by_task_created_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
