# Generated by Django 3.2.7 on 2021-09-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
