# Generated by Django 3.2.7 on 2021-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0003_auto_20210923_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'TODO'), (2, 'READY'), (3, 'IN PROGRESS'), (4, 'COMPLETED')], default='1'),
        ),
    ]
