# Generated by Django 3.2.7 on 2021-10-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0004_task_life_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='life_time',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
