# Generated by Django 3.2.7 on 2021-11-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0006_alter_task_life_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('3_LOW', 'LOW'), ('2_NORMAL', 'NORMAL'), ('1_HIGH', 'HIGH')], default='1_HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1_TO_DO', 'TO_DO'), ('2_READY', 'READY'), ('3_IN_PROGRESS', 'IN_PROGRESS'), ('4_COMPLETED', 'COMPLETED')], default='1_TO_DO', max_length=20),
        ),
    ]
