# Generated by Django 3.2.7 on 2021-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'HIGH'), (2, 'NORMAL'), (1, 'LOW')], default='1'),
        ),
    ]
