# Generated by Django 3.2.7 on 2021-09-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_accounting_sys', '0006_task_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default='1'),
        ),
    ]
